name: freshResolvers

on:
  schedule:
  # Run daily
    - cron:  '30 14 * * *' #'*/3 * * * *'#

jobs:
  resfresh-list:
    runs-on: ubuntu-20.04
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
    
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITTOKEN }}

      - name: Checkout DNS Validator
        uses: actions/checkout@v2
        with:
          repository: 'vortexau/dnsvalidator'
          path: dnsvalidator
    
      - name: Install DNS Validator
        run: |
          cd dnsvalidator
          python3 setup.py install
      
      - name: Install contextvars
        run: pip3 install contextvars
    
      - name: Generate new resolvers
        run: timeout 3600 dnsvalidator -tL https://public-dns.info/nameservers.txt -threads 900 --silent -o ~/resolvers.txt
    
      - name: Set current date
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: Commit changes
        run: |
          mv ~/resolvers.txt .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add resolvers.txt
          git commit -m "${NOW} update"
    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITTOKEN }}
          branch: main
